// This file is @generated by prost-build.
/// 全局集群服务事件
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterDataProto {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub time: i64,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<DataValueProto>,
}
/// 整个产品统一的数据值格式
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataValueProto {
    #[prost(oneof = "data_value_proto::DataValue", tags = "1, 2, 3, 4, 5")]
    pub data_value: ::core::option::Option<data_value_proto::DataValue>,
}
/// Nested message and enum types in `DataValueProto`.
pub mod data_value_proto {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum DataValue {
        #[prost(bool, tag = "1")]
        Bool(bool),
        #[prost(int64, tag = "2")]
        Long(i64),
        #[prost(double, tag = "3")]
        Double(f64),
        #[prost(string, tag = "4")]
        String(::prost::alloc::string::String),
        #[prost(string, tag = "5")]
        Json(::prost::alloc::string::String),
    }
}
