// This file is @generated by prost-build.
/// 全局集群服务事件
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClusterEventProto {
    #[prost(int64, tag = "1")]
    pub ts: i64,
    #[prost(oneof = "cluster_event_proto::ClusterEvent", tags = "2, 3")]
    pub cluster_event: ::core::option::Option<cluster_event_proto::ClusterEvent>,
}
/// Nested message and enum types in `ClusterEventProto`.
pub mod cluster_event_proto {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum ClusterEvent {
        #[prost(message, tag = "2")]
        UserEvent(super::UserEvent),
        #[prost(message, tag = "3")]
        GroupEvent(super::GroupEvent),
    }
}
/// //////////////////////////////// 用户事件 //////////////////////////////////////////
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UserEvent {}
/// //////////////////////////////// 组织事件 //////////////////////////////////////////
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GroupEvent {}
